[package]
name = "socket"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.18"
fast_collections = "0.52.0"
fast_delegate = "0.11.0"
mio = { version = "1.0.0", features = ["net", "os-poll"] }
nonmax = "0.5.5"
packetize = { version = "0.33.0", features = ["stream"] }

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "benchmark"
harness = false
