[package]
name = "socket_server"
version = "0.2.0"
edition = "2021"
description = "single thread selector server socket"
author = "Bruce0203 <brucefreedy@gmail.com>"
repository = "https://github.com/Bruce0203/socket-server"
license = "MIT"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
derive_more = "0.99.18"
fast_collections = "0.52.0"
mio = { version = "1.0.0", features = ["net", "os-poll"] }
nonmax = "0.5.5"
httparse = { version = "1.9.4", optional = true }
sha1 = { version = "0.10.6", optional = true }
data-encoding = { version = "2.6.0", optional = true }
packetize = { version = "0.42.0", features = ["stream"] }

[features]
default = ["websocket"]
websocket = ["dep:httparse", "dep:data-encoding", "dep:sha1"]

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "benchmark"
harness = false
